CREATE TABLE "ABBADev Consultation Leads" (
  "Lead" TITLE,
  "Status" STATUS,
  "Priority" SELECT('High':red, 'Medium':yellow, 'Low':green),
  "Score" NUMBER,
  "Submitted At" DATE,
  "Name" RICH_TEXT,
  "Email" EMAIL,
  "Company" RICH_TEXT,
  "Preferred Contact" SELECT('Email':blue, 'Phone':green, 'Video call':purple),
  "Work Focus" SELECT('AI automation':blue, 'Custom software':green, 'Architecture review':purple, 'Digital transformation':orange),
  "Company Stage" SELECT('Growing business':blue, 'Startup':green, 'Enterprise team':purple, 'Public sector or nonprofit':orange),
  "Urgency" SELECT('This month':red, 'This quarter':yellow, 'Planning phase':blue, 'Exploring options':gray),
  "Engagement" SELECT('Consultation and roadmap':blue, 'Architecture review':purple, 'Prototype or proof of concept':yellow, 'Full software build':green),
  "Budget" SELECT('To be scoped':gray, 'Under $5k':blue, '$5k to $15k':yellow, '$15k to $50k':orange, '$50k+':red),
  "Current Tools" RICH_TEXT,
  "Challenge" RICH_TEXT,
  "Score Reasons" RICH_TEXT,
  "Source" SELECT('abbadev.com':blue),
  "Source Page" URL,
  "Next Action" RICH_TEXT,
  "Owner" PEOPLE,
  "Last Contacted" DATE
)
